spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 600000
      pool-name: DatabookHikariCP
      max-lifetime: 28740000
      connection-test-query: SELECT 1
    driver-class-name: com.mysql.jdbc.Driver
    data-username: root
    data-password: MiMa1234
    url: jdbc:mysql://39.106.20.195:3306/muxin-dev?useUnicode=true&characterEncoding=utf8&useSSL=false

mybatis:
  type-aliases-package: com.im.muxin.pojo
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers:
  - com.im.muxin.util.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

